apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ops-lab-1
  labels:
    app: dev-ops-lab-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-ops-lab-1
  template:
    metadata:
      labels:
        app: dev-ops-lab-1
    spec:
      containers:
        - name: dev-ops-lab-1
          image: vadymprokhorchuk/dev-ops-lab-1:latest
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-configs
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-configs
          configMap:
            name: nginx-config