name: Check code & push to Docker Hub
on: push
jobs:
  check_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Init
        run: npm ci

      - name: Check code
        run: npm run lint

      - name: Build image
        run: docker build . -t dev-ops-lab-1:latest

      - name: Docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Tag image
        run: sudo docker tag dev-ops-lab-1:latest ${{secrets.DOCKERHUB_USERNAME}}/dev-ops-lab-1:latest

      - name: Docker push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/dev-ops-lab-1:latest

#  pull_and_run_image:
#    needs: check_and_push
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Docker login
#        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
#
#      - name: Download image
#        run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/dev-ops-lab-1
#
#      - name: Build image
#        run: docker build . -t dev-ops-lab-1:latest
#
#      - name: Run container
#        run: docker run -p 80:80 -m 924m --cpus=0.3 -d --rm --env-file ./.env dev-ops-lab-1:latest
#
#      - name: Make request
#        run: |
#          curl -X GET "http://0.0.0.0/"