name: Check code & push to Docker Hub
on: push
jobs:
  check_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Init
        run: npm ci

      - name: Check code
        run: npm run lint

      - name: Build image
        run: docker build . -t dev-ops-lab-1:latest

      - name: Docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Docker push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/dev-ops-lab-1:latest